/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package autonoma.ProyectoFinal.views;

import javax.swing.*;
import java.awt.*;

public class PantallaDificultad extends JPanel {

    private Image fondo;
    private JFrame ventana;

    public PantallaDificultad(JFrame ventana) {
        this.ventana = ventana;
        setLayout(null);
        setPreferredSize(new Dimension(900, 700));

        // Fondo
        try {
            fondo = new ImageIcon(getClass().getResource("/autonoma/ProyectoFinal/resources/menu_fondo.png")).getImage();
        } catch (Exception e) {
            fondo = null;
        }

        int panelAncho = 900;
        int botonAncho = 200;
        int xCentro = (panelAncho - botonAncho) / 2;

        // Botón Fácil
        JButton facil = new JButton("Fácil");
        facil.setBounds(xCentro, 300, botonAncho, 40);
        add(facil);

        // Botón Media
        JButton media = new JButton("Media");
        media.setBounds(xCentro, 370, botonAncho, 40);
        add(media);

        // Botón Difícil
        JButton dificil = new JButton("Difícil");
        dificil.setBounds(xCentro, 440, botonAncho, 40);
        add(dificil);

        // Acciones
        facil.addActionListener(e -> iniciarJuego(1));
        media.addActionListener(e -> iniciarJuego(2));
        dificil.addActionListener(e -> iniciarJuego(3));
    }

    private void iniciarJuego(int dificultad) {
        Juego juego = new Juego(dificultad);
        ventana.setContentPane(juego);
        ventana.revalidate();
        ventana.pack();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);

        // 🔥 Esto permite que el panel `Juego` reciba las teclas
        juego.requestFocusInWindow();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (fondo != null) {
            g.drawImage(fondo, 0, 0, getWidth(), getHeight(), this);
        }
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
