/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package autonoma.ProyectoFinal.views;

import javax.swing.*;
import java.awt.*;

/**
 * Pantalla para seleccionar la dificultad del juego.
 */
public class PantallaDificultad extends JPanel {

    private Image fondo;

    public PantallaDificultad(JFrame frame) {
        setLayout(null);
        setPreferredSize(new Dimension(800, 600));

        // Fondo
        try {
            fondo = new ImageIcon(getClass().getResource("/autonoma/ProyectoFinal/resources/menu_fondo.png")).getImage();
        } catch (Exception e) {
            fondo = null;
        }

        

        // Botones bajados visualmente
        JButton facil = new JButton("Fácil");
        JButton media = new JButton("Media");
        JButton dificil = new JButton("Difícil");

        facil.setBounds(300, 240, 200, 40);
        media.setBounds(300, 300, 200, 40);
        dificil.setBounds(300, 360, 200, 40);

        add(facil);
        add(media);
        add(dificil);

        // Acciones
        facil.addActionListener(e -> iniciarJuego(frame, 1));
        media.addActionListener(e -> iniciarJuego(frame, 2));
        dificil.addActionListener(e -> iniciarJuego(frame, 3));
    }

    private void iniciarJuego(JFrame frame, int dificultad) {
        Juego juego = new Juego(dificultad);
        frame.setContentPane(juego);
        frame.revalidate();
        juego.requestFocusInWindow();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (fondo != null) {
            g.drawImage(fondo, 0, 0, getWidth(), getHeight(), this);
        }
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
